=== RAWeber/Unity/Game00/Assets/Scripts/New System/Item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Item">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ItemID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="05iuWFaBwU6kpw3hs2Kahg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADTmK5YVoHBTqSnDeGzYpqGAAAAAGGqIyt3qeRAAAAAAAAAAABJAHQA
ZQBtAAAAAAAAAHKmQGC0EGBDpZa9WIasDQwHAAAA05iuWFaBwU6kpw3hs2KahkkA
dABlAG0ASQBEAAAAAAAAAEpueddEqcJCkk5oXg83O28HAAAA05iuWFaBwU6kpw3h
s2KahkkAdABlAG0ATgBhAG0AZQAAAAAAAACWuNRWZSL+Ro+R3xriaJ4NBwAAANOY
rlhWgcFOpKcN4bNimoZJAHQAZQBtAFQAeQBwAGUAAAAAAAAAswy2dtnJMEW5Jqn3
+l0kzgcAAADTmK5YVoHBTqSnDeGzYpqGUwB1AGIAVAB5AHAAZQAAAAAAAABgb3VV
SAhdSoDnlNDzT1MtBwAAANOYrlhWgcFOpKcN4bNimoZBAHQAdABhAGMAawAAAAAA
AABU9ZrgdRY1SauiDn2XmvkiBwAAANOYrlhWgcFOpKcN4bNimoZBAHQAdABhAGMA
awBTAHAAZQBlAGQAAAAAAAAAfY1jIpPMJkyMBwyTynesDgcAAADTmK5YVoHBTqSn
DeGzYpqGUgBhAG4AZwBlAAAAAAAAAPrdYmKJv0VOi+X4abBBVT0HAAAA05iuWFaB
wU6kpw3hs2Kahk0AYQB4AFMAaQB6AGUAAAAAAAAAO4AtSKmDg0S1bmHSz2/WBQcA
AADTmK5YVoHBTqSnDeGzYpqGRABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ItemID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="cqZAYLQQYEOllr1YhqwNDA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Sm5510SpwkKSTmheDzc7bw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ItemType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="lrjUVmUi/kaPkd8a4mieDQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SubType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="swy2dtnJMEW5Jqn3+l0kzg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Attack" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="YG91VUgIXUqA55TQ809TLQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AttackSpeed" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="VPWa4HUWNUmrog59l5r5Ig==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Range" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Fixed"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="1"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="fY1jIpPMJkyMBwyTynesDg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MaxSize" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="+t1iYom/RU6L5fhpsEFVPQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Description" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="O4AtSKmDg0S1bmHSz2/WBQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== RAWeber/Unity/Game00/Assets/Scripts/New System/Item.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Item.xsd" generated="2015-11-11T11:48:31">
<Item>
<ItemID>1</ItemID>
<ItemName>Basic Sword</ItemName>
<ItemType>WEAPON</ItemType>
<SubType>SWORD</SubType>
<Attack>5</Attack>
<AttackSpeed>1.2</AttackSpeed>
<Range>1</Range>
<MaxSize>1</MaxSize>
<Description>Basic well balanced sword</Description>
<Relic01>Basic Blade</Relic01>
<Relic02>Sword Hilt</Relic02>
</Item>
<Item>
<ItemID>2</ItemID>
<ItemName>Great Sword</ItemName>
<ItemType>WEAPON</ItemType>
<SubType>SWORD</SubType>
<Attack>7</Attack>
<AttackSpeed>0.6</AttackSpeed>
<Range>1.7</Range>
<MaxSize>1</MaxSize>
<Description>Large powerful sword, but very slow</Description>
<Relic01>Large Blade</Relic01>
<Relic02>Sword Hilt</Relic02>
</Item>
<Item>
<ItemID>3</ItemID>
<ItemName>Longsword</ItemName>
<ItemType>WEAPON</ItemType>
<SubType>SWORD</SubType>
<Attack>6</Attack>
<AttackSpeed>0.7</AttackSpeed>
<Range>2.2</Range>
<MaxSize>1</MaxSize>
<Description>Great reach, but slower</Description>
<Relic01>Long Blade</Relic01>
<Relic02>Sword Hilt</Relic02>
</Item>
<Item>
<ItemID>5</ItemID>
<ItemName>Health Potion</ItemName>
<ItemType>CONSUMABLE</ItemType>
<SubType>HEALTH</SubType>
<Attack>0</Attack>
<AttackSpeed>0</AttackSpeed>
<Range>0</Range>
<MaxSize>3</MaxSize>
<Description>Restores health</Description>
</Item>
<Item>
<ItemID>6</ItemID>
<ItemName>Mana Potion</ItemName>
<ItemType>CONSUMABLE</ItemType>
<SubType>MANA</SubType>
<Attack>0</Attack>
<AttackSpeed>0</AttackSpeed>
<Range>0</Range>
<MaxSize>1</MaxSize>
<Description>Restores mana</Description>
</Item>
<Item>
<ItemID>7</ItemID>
<ItemName>Sword Hilt</ItemName>
<ItemType>RELIC</ItemType>
<SubType>WEAPON</SubType>
<Attack>5</Attack>
<AttackSpeed>0</AttackSpeed>
<Range>0</Range>
<MaxSize>1</MaxSize>
<Description>Sword relic</Description>
</Item>
<Item>
<ItemID>8</ItemID>
<ItemName>Basic Blade</ItemName>
<ItemType>RELIC</ItemType>
<SubType>WEAPON</SubType>
<Attack>0</Attack>
<AttackSpeed>0.2</AttackSpeed>
<Range>0</Range>
<MaxSize>1</MaxSize>
<Description>Sword relic</Description>
</Item>
</dataroot>
