=== RAWeber/Unity/Game00/Assets/Scripts/Items/DataBase/Item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Item">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ItemID" index-key="ItemID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ItemID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="GRWUkIH2+0+caFlbOyMFWg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAZFZSQgfb7T5xoWVs7IwVaAAAAAJVsE2o2ruRAAAAAAAAAAABJAHQA
ZQBtAAAAAAAAADrzpf0fnBtJtIBakkF6uzsHAAAAGRWUkIH2+0+caFlbOyMFWkkA
dABlAG0ASQBEAAAAAAAAAIn/IdX2vUNFmfYdZdbUMRAHAAAAGRWUkIH2+0+caFlb
OyMFWkkAdABlAG0AVAB5AHAAZQAAAAAAAACT4Z9EqiacRp/UbvHEa8s+BwAAABkV
lJCB9vtPnGhZWzsjBVpJAHQAZQBtAE4AYQBtAGUAAAAAAAAAUbcj9xw8LUmNzMws
vvDOlwcAAAAZFZSQgfb7T5xoWVs7IwVaUwB1AGIAVAB5AHAAZQAAAAAAAAC0upSx
PEFBQKJXtEF4Bh7MBwAAABkVlJCB9vtPnGhZWzsjBVpCAGEAcwBlAFMAdABhAHQA
MQAAAAAAAADbDwqVabLISJ/Mj3j5W515BwAAABkVlJCB9vtPnGhZWzsjBVpCAGEA
cwBlAFMAdABhAHQAMgAAAAAAAABBlUJXBbQRT7slaBKgk7AGBwAAABkVlJCB9vtP
nGhZWzsjBVpCAGEAcwBlAFMAdABhAHQAMwAAAAAAAABuXWMDqCkBTJrVB4Cfmx20
BwAAABkVlJCB9vtPnGhZWzsjBVpCAGEAcwBlAFMAdABhAHQANAAAAAAAAACUh45I
SsT9TKVNiqFtaSbRBwAAABkVlJCB9vtPnGhZWzsjBVpNAGEAeABTAGkAegBlAAAA
AAAAAP61mx0I8fpNi5wUir3P4q4HAAAAGRWUkIH2+0+caFlbOyMFWkQAZQBzAGMA
cgBpAHAAdABpAG8AbgAAAAAAAACj04+sAGeGQo3FMU1FgmAZBwAAABkVlJCB9vtP
nGhZWzsjBVpSAGUAbABpAGMAMAAxAAAAAAAAAB7UJSmKn49PptZANv29uoMHAAAA
GRWUkIH2+0+caFlbOyMFWlIAZQBsAGkAYwAwADIAAAAAAAAAF7Eqe+gaskimehDL
/bwdMgcAAAAZFZSQgfb7T5xoWVs7IwVaUgBlAGwAaQBjADAAMwAAAAAAAAD1OCSm
L3f0Qpn3OtVWIoSZBwAAABkVlJCB9vtPnGhZWzsjBVpSAGUAbABpAGMAMAA0AAAA
AAAAACAK4Fm8h0dOkdZvHOlxuaIHAAAAGRWUkIH2+0+caFlbOyMFWlIAZQBsAGkA
YwAwADUAAAAAAAAABEejeDmHjUCAr6LIBbQPfwcAAAAZFZSQgfb7T5xoWVs7IwVa
UQB1AGEAbABpAHQAeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAA
AAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ItemID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="OvOl/R+cG0m0gFqSQXq7Ow==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="if8h1fa9Q0WZ9h1l1tQxEA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="k+GfRKomnEaf1G7xxGvLPg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2070"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SubType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Ubcj9xw8LUmNzMwsvvDOlw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Quality" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="BEejeDmHjUCAr6LIBbQPfw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="BaseStat1" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="tLqUsTxBQUCiV7RBeAYezA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="BaseStat2" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="2w8KlWmyyEifzI94+VudeQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="BaseStat3" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="QZVCVwW0EU+7JWgSoJOwBg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="BaseStat4" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="bl1jA6gpAUya1QeAn5sdtA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MaxSize" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="lIeOSErE/UylTYqhbWkm0Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Description" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="/rWbHQjx+k2LnBSKvc/irg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="11"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Relic01" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="o9OPrABnhkKNxTFNRYJgGQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="12"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Relic02" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="HtQlKYqfj0+m1kA2/b26gw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="13"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Relic03" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="F7Eqe+gaskimehDL/bwdMg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="14"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Relic04" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="9Tgkpi939EKZ9zrVViKEmQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="15"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Relic05" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="IArgWbyHR06R1m8c6XG5og==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="16"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== RAWeber/Unity/Game00/Assets/Scripts/New System/Items/DataBase/Item.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Item.xsd" generated="2015-12-16T12:47:37">
<Item>
<ItemID>12</ItemID>
<ItemType>RELIC</ItemType>
<ItemName>Basic Palm Plate</ItemName>
<SubType>ARMOR</SubType>
<Quality>COMMON</Quality>
<MaxSize>1</MaxSize>
<Description>Glove relic</Description>
</Item>
<Item>
<ItemID>13</ItemID>
<ItemType>RELIC</ItemType>
<ItemName>Glove Piece</ItemName>
<SubType>ARMOR</SubType>
<Quality>COMMON</Quality>
<MaxSize>1</MaxSize>
<Description>Glove relic</Description>
</Item>
<Item>
<ItemID>1</ItemID>
<ItemType>CONSUMABLE</ItemType>
<ItemName>Health Potion</ItemName>
<SubType>HEALTH</SubType>
<Quality>COMMON</Quality>
<BaseStat1>50</BaseStat1>
<MaxSize>3</MaxSize>
<Description>Restores health</Description>
</Item>
<Item>
<ItemID>2</ItemID>
<ItemType>CONSUMABLE</ItemType>
<ItemName>Mana Potion</ItemName>
<SubType>MANA</SubType>
<Quality>COMMON</Quality>
<BaseStat1>50</BaseStat1>
<MaxSize>1</MaxSize>
<Description>Restores mana</Description>
</Item>
<Item>
<ItemID>3</ItemID>
<ItemType>EQUIPMENT</ItemType>
<ItemName>Basic Helmet</ItemName>
<SubType>HELM</SubType>
<Quality>COMMON</Quality>
<BaseStat1>75</BaseStat1>
<MaxSize>1</MaxSize>
<Description>Basic well balenced helm</Description>
<Relic01>Basic Face Plate</Relic01>
<Relic02>Helm Piece</Relic02>
</Item>
<Item>
<ItemID>4</ItemID>
<ItemType>RELIC</ItemType>
<ItemName>Basic Blade</ItemName>
<SubType>WEAPON</SubType>
<Quality>COMMON</Quality>
<MaxSize>1</MaxSize>
<Description>Sword relic</Description>
</Item>
<Item>
<ItemID>5</ItemID>
<ItemType>RELIC</ItemType>
<ItemName>Basic Face Plate</ItemName>
<SubType>ARMOR</SubType>
<Quality>COMMON</Quality>
<MaxSize>1</MaxSize>
<Description>Helm relic</Description>
</Item>
<Item>
<ItemID>6</ItemID>
<ItemType>RELIC</ItemType>
<ItemName>Helm Piece</ItemName>
<SubType>ARMOR</SubType>
<Quality>COMMON</Quality>
<MaxSize>1</MaxSize>
<Description>Helm relic</Description>
</Item>
<Item>
<ItemID>7</ItemID>
<ItemType>RELIC</ItemType>
<ItemName>Sword Hilt</ItemName>
<SubType>WEAPON</SubType>
<Quality>COMMON</Quality>
<MaxSize>1</MaxSize>
<Description>Sword relic</Description>
</Item>
<Item>
<ItemID>8</ItemID>
<ItemType>WEAPON</ItemType>
<ItemName>Basic Sword</ItemName>
<SubType>SWORD</SubType>
<Quality>COMMON</Quality>
<BaseStat1>25</BaseStat1>
<BaseStat2>10</BaseStat2>
<BaseStat3>10</BaseStat3>
<BaseStat4>1</BaseStat4>
<MaxSize>1</MaxSize>
<Description>Basic well balanced sword</Description>
<Relic01>Basic Blade</Relic01>
<Relic02>Sword Hilt</Relic02>
</Item>
<Item>
<ItemID>9</ItemID>
<ItemType>WEAPON</ItemType>
<ItemName>Great Sword</ItemName>
<SubType>SWORD</SubType>
<Quality>COMMON</Quality>
<BaseStat1>75</BaseStat1>
<BaseStat2>6</BaseStat2>
<BaseStat3>17</BaseStat3>
<BaseStat4>2</BaseStat4>
<MaxSize>1</MaxSize>
<Description>Large powerful sword, but very slow</Description>
<Relic01>Large Blade</Relic01>
<Relic02>Sword Hilt</Relic02>
</Item>
<Item>
<ItemID>10</ItemID>
<ItemType>WEAPON</ItemType>
<ItemName>Longsword</ItemName>
<SubType>SWORD</SubType>
<Quality>COMMON</Quality>
<BaseStat1>50</BaseStat1>
<BaseStat2>7</BaseStat2>
<BaseStat3>22</BaseStat3>
<BaseStat4>2</BaseStat4>
<MaxSize>1</MaxSize>
<Description>Great reach, but slower</Description>
<Relic01>Long Blade</Relic01>
<Relic02>Sword Hilt</Relic02>
</Item>
<Item>
<ItemID>11</ItemID>
<ItemType>EQUIPMENT</ItemType>
<ItemName>Basic Gloves</ItemName>
<SubType>GLOVES</SubType>
<Quality>COMMON</Quality>
<BaseStat1>25</BaseStat1>
<MaxSize>1</MaxSize>
<Description>Basic well balenced gloves</Description>
<Relic01>Basic Palm Plate</Relic01>
<Relic02>Glove piece</Relic02>
</Item>
</dataroot>
